export const murderDescriptions = [
	"A body lies slumped over a wooden desk, blood pooling across scattered papers.",
	"A man is found face-down in a muddy alley, a single bullet wound in his back.",
	"A woman lies motionless at the foot of a grand staircase, her neck twisted unnaturally.",
	"A lifeless figure floats in a murky pond, tangled in reeds and trash.",
	"A body is discovered in a hotel room, the bed sheets soaked through with blood.",
	"A man sits propped against a brick wall, a knife buried deep in his chest.",
	"A woman is found in a dimly lit kitchen, shattered glass and blood everywhere.",
	"A body dangles from an old oak tree, swaying slightly in the breeze.",
	"A corpse lies hidden beneath a collapsed shelf in a dusty library.",
	"A man is found inside a locked car, a thin line of blood trailing from his mouth.",
	"A figure lies sprawled across a cracked concrete floor, a gun tossed nearby.",
	"A woman is slumped in a bathtub full of crimson water, eyes staring blankly upward.",
	"A body is buried in a shallow grave, hands still reaching toward the surface.",
	"A man lies crumpled at the base of a cliff, rocks slick with blood.",
	"A woman is found seated at a dining table, a glass of wine spilled across the floor.",
	"A corpse lies behind a rundown gas station, half-covered in trash bags.",
	"A body is stuffed into a small closet, limbs bent at unnatural angles.",
	"A figure lies sprawled on a rain-soaked street, footprints fading into the darkness.",
	"A man is found tied to a chair in an abandoned warehouse, blood splattered on the walls.",
	"A woman lies face-up in a flower garden, a deep stab wound to her chest."
]